// Downloads/projeto-final-Integrador/components/global/footer/Footer.vue
<template>
  <footer class="footer">
    <div class="container">
      <div class="footer-content">
        <div class="footer-brand">
          <img src="/logo.png" alt="Serviflix Logo" class="footer-logo">
          <p class="footer-description">
            Conectando talentos a oportunidades reais. A plataforma que facilita a vida de profissionais autônomos e clientes em busca de serviços de qualidade.
          </p>
        </div>

        <div class="footer-links">
          <div class="link-group">
            <h4 class="link-title">Plataforma</h4>
            <a href="#" class="footer-link">Como Funciona</a>
            <a href="#" class="footer-link">Categorias</a>
            <a href="#" class="footer-link">Preços</a>
            <a href="#" class="footer-link">Segurança</a>
          </div>

          <div class="link-group">
            <h4 class="link-title">Empresa</h4>
            <a href="#" class="footer-link">Sobre Nós</a>
            <a href="#" class="footer-link">Carreiras</a>
            <a href="#" class="footer-link">Blog</a>
            <a href="#" class="footer-link">Contato</a>
          </div>

          <div class="link-group">
            <h4 class="link-title">Suporte</h4>
            <a href="#" class="footer-link">Central de Ajuda</a>
            <a href="#" class="footer-link">Termos de Uso</a>
            <a href="#" class="footer-link">Privacidade</a>
            <a href="#" class="footer-link">FAQ</a>
          </div>
        </div>
      </div>

      <div class="footer-bottom">
        <p class="copyright">© 2024 Serviflix. Todos os direitos reservados.</p>
        <div class="footer-social">
          <a href="#" class="social-link">Instagram</a>
          <a href="#" class="social-link">Facebook</a>
          <a href="#" class="social-link">LinkedIn</a>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup></script>

<style scoped>
.footer {
  background: var(--cor-cinza-escuro);
  color: var(--cor-branco);
  padding: 4rem 0 2rem;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 2rem;
}

.footer-content {
  display: grid;
  grid-template-columns: 1fr 2fr;
  gap: 4rem;
  margin-bottom: 3rem;
}

.footer-brand {
  max-width: 300px;
}

.footer-logo {
  height: 80px;
  margin-bottom: 1.5rem;
  filter: brightness(0) invert(1);
  transition: transform 0.3s ease;
  cursor: pointer;
}

.footer-logo:hover {
  transform: scale(1.05);
}

.footer-description {
  font-family: var(--regular);
  font-size: var(--f2);
  color: var(--cor-cinza-2);
  line-height: 1.6;
}

.footer-links {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 2rem;
}

.link-group {
  display: flex;
  flex-direction: column;
}

.link-title {
  font-family: var(--bold);
  font-size: var(--f3);
  color: var(--cor-branco);
  margin-bottom: 1rem;
}

.footer-link {
  font-family: var(--regular);
  font-size: var(--f2);
  color: var(--cor-cinza-2);
  text-decoration: none;
  margin-bottom: 0.5rem;
  transition: color 0.3s;
}

.footer-link:hover {
  color: var(--cor-azul-principal);
}

.footer-bottom {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-top: 2rem;
  border-top: 1px solid var(--cor-cinza);
}

.copyright {
  font-family: var(--regular);
  font-size: var(--f1);
  color: var(--cor-cinza-2);
}

.footer-social {
  display: flex;
  gap: 1.5rem;
}

.social-link {
  font-family: var(--regular);
  font-size: var(--f2);
  color: var(--cor-cinza-2);
  text-decoration: none;
  transition: color 0.3s;
}

.social-link:hover {
  color: var(--cor-azul-principal);
}

/* Responsivo */
@media screen and (max-width: 768px) {
  .footer-content {
    grid-template-columns: 1fr;
    gap: 2rem;
  }

  .footer-links {
    grid-template-columns: 1fr;
    gap: 1.5rem;
  }

  .footer-bottom {
    flex-direction: column;
    gap: 1rem;
    text-align: center;
  }

  .container {
    padding: 0 1rem;
  }
}
</style>

// Downloads/projeto-serviflex-main (1)/projeto-serviflex-main/src/components/Footer.tsx
import React from 'react';
import { FacebookIcon, InstagramIcon, TwitterIcon, LinkedinIcon, MailIcon, PhoneIcon, MapPinIcon } from 'lucide-react';
export function Footer() {
  const footerLinks = {
    'Para Clientes': ['Como Contratar', 'Buscar Profissionais', 'Projetos', 'Garantias', 'Pagamentos'],
    'Para Profissionais': ['Como Vender', 'Criar Perfil', 'Dicas de Sucesso', 'Comunidade', 'Ferramentas'],
    Empresa: ['Sobre Nós', 'Carreiras', 'Imprensa', 'Blog', 'Parceiros'],
    Suporte: ['Central de Ajuda', 'Segurança', 'Termos de Uso', 'Política de Privacidade', 'Contato']
  };
  return <footer className="w-full bg-[#0F172A] text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Main Footer Content */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-8 mb-12">
          {/* Brand Section */}
          <div className="lg:col-span-1">
            <div className="flex items-center gap-3 mb-4">
              <img src="/logo.png" alt="ServeFlex Logo" className="w-10 h-10 object-contain" />
              <h3 className="text-2xl font-bold text-white">ServiFlex</h3>
            </div>
            <p className="text-white/70 mb-6">
              Conectando talentos com oportunidades desde 2024.
            </p>
            <div className="flex space-x-4">
              <a href="#" className="w-10 h-10 bg-white/10 rounded-full flex items-center justify-center hover:bg-[#2563EB] transition-colors">
                <FacebookIcon className="w-5 h-5" />
              </a>
              <a href="#" className="w-10 h-10 bg-white/10 rounded-full flex items-center justify-center hover:bg-[#2563EB] transition-colors">
                <InstagramIcon className="w-5 h-5" />
              </a>
              <a href="#" className="w-10 h-10 bg-white/10 rounded-full flex items-center justify-center hover:bg-[#2563EB] transition-colors">
                <TwitterIcon className="w-5 h-5" />
              </a>
              <a href="#" className="w-10 h-10 bg-white/10 rounded-full flex items-center justify-center hover:bg-[#2563EB] transition-colors">
                <LinkedinIcon className="w-5 h-5" />
              </a>
            </div>
          </div>
          {/* Links Sections */}
          {Object.entries(footerLinks).map(([category, links]) => <div key={category}>
              <h4 className="font-semibold text-white mb-4">{category}</h4>
              <ul className="space-y-2">
                {links.map(link => <li key={link}>
                    <a href="#" className="text-white/70 hover:text-[#2563EB] transition-colors text-sm">
                      {link}
                    </a>
                  </li>)}
              </ul>
            </div>)}
        </div>
        {/* Contact Info */}
        <div className="border-t border-white/10 pt-8 mb-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-[#2563EB] rounded-lg flex items-center justify-center">
                <MailIcon className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="text-sm text-white/70">Email</p>
                <p className="text-white font-medium">contato@serveflex.com</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-[#2563EB] rounded-lg flex items-center justify-center">
                <PhoneIcon className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="text-sm text-white/70">Telefone</p>
                <p className="text-white font-medium">(11) 9999-9999</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-[#2563EB] rounded-lg flex items-center justify-center">
                <MapPinIcon className="w-5 h-5 text-white" />
              </div>
              <div>
                <p className="text-sm text-white/70">Endereço</p>
                <p className="text-white font-medium">São Paulo, SP - Brasil</p>
              </div>
            </div>
          </div>
        </div>
        {/* Bottom Bar */}
        <div className="border-t border-white/10 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-white/70 text-sm">
            © 2024 ServiFlex. Todos os direitos reservados.
          </p>
          <div className="flex gap-6">
            <a href="#" className="text-white/70 hover:text-[#2563EB] text-sm transition-colors">
              Termos de Serviço
            </a>
            <a href="#" className="text-white/70 hover:text-[#2563EB] text-sm transition-colors">
              Política de Privacidade
            </a>
            <a href="#" className="text-white/70 hover:text-[#2563EB] text-sm transition-colors">
              Cookies
            </a>
          </div>
        </div>
      </div>
    </footer>;
}
